export const CITYLIST = [
  '臺北市',
  '新北市',
  '桃園市',
  '臺中市',
  '臺南市',
  '高雄市',
  '宜蘭縣',
  '新竹縣',
  '苗栗縣',
  '彰化縣',
  '南投縣',
  '雲林縣',
  '嘉義縣',
  '屏東縣',
  '花蓮縣',
  '臺東縣',
  '澎湖縣',
  '基隆市',
  '新竹市',
  '嘉義市',
];

export const THEMELIST = [
  { label: '觀光工廠類', src: '' },
  { label: '文化類', src: '' },
  { label: '遊憩類', src: '' },
  { label: '體育健身類', src: '' },
  { label: '都會公園類', src: '' },
  { label: '自然風景類', src: '' },
  { label: '國家風景區類', src: '' },
  { label: '國家公園類', src: '' },
  { label: '廟宇類', src: '' },
  { label: '小吃/特產類', src: '' },
  { label: '生態類', src: '' },
  { label: '古蹟類', src: '' },
  { label: '休閒農業類', src: '' },
  { label: '藝術類', src: '' },
  { label: '森林遊樂區類', src: '' },
  { label: '林場類', src: '' },
  { label: '其他', src: '' },
];
